//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/cyril/RiderProjects/HomeWork1/PasLexer/Pascal.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class Pascal : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		IDENTIFIER=1, COMMENT=2, CHARACTERSTRING=3, NUMBER=4, WHITESPACE=5;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"IDENTIFIER", "COMMENT", "COMMENT_1", "COMMENT_2", "COMMENT_3", "CHARACTERSTRING", 
		"NUMBER", "UNSIGNEDNUMBER", "SIGNEDNUMBER", "UNSIGNEDINTEGER", "UNSIGNEDREAL", 
		"BINARYSEQUENCE", "OCTALSEQUENCE", "DIGITSEQ", "HEXSEQUENCE", "SIGN", 
		"SCALE", "WHITESPACE"
	};


	public Pascal(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Pascal(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "IDENTIFIER", "COMMENT", "CHARACTERSTRING", "NUMBER", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Pascal.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Pascal() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\a', '\xBB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '*', '\n', '\x2', '\f', 
		'\x2', '\xE', '\x2', '-', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x32', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\x38', '\n', '\x4', '\f', '\x4', 
		'\xE', '\x4', ';', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'?', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x42', '\v', '\x4', '\x3', 
		'\x4', '\a', '\x4', '\x45', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 'H', 
		'\v', '\x4', '\x5', '\x4', 'J', '\n', '\x4', '\x3', '\x4', '\a', '\x4', 
		'M', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 'P', '\v', '\x4', '\x3', 
		'\x4', '\a', '\x4', 'S', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 'V', 
		'\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\a', '\x5', ']', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '`', 
		'\v', '\x5', '\x3', '\x5', '\x5', '\x5', '\x63', '\n', '\x5', '\x3', '\x5', 
		'\a', '\x5', '\x66', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'i', '\v', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\a', '\x6', 'q', '\n', '\x6', '\f', '\x6', '\xE', 
		'\x6', 't', '\v', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 'x', '\n', 
		'\a', '\f', '\a', '\xE', '\a', '{', '\v', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x5', '\b', '\x81', '\n', '\b', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', '\x85', '\n', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', 
		'\v', '\x8E', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x5', '\f', '\x94', '\n', '\f', '\x5', '\f', '\x96', '\n', '\f', 
		'\x3', '\f', '\x5', '\f', '\x99', '\n', '\f', '\x3', '\r', '\x3', '\r', 
		'\x6', '\r', '\x9D', '\n', '\r', '\r', '\r', '\xE', '\r', '\x9E', '\x3', 
		'\xE', '\x3', '\xE', '\x6', '\xE', '\xA3', '\n', '\xE', '\r', '\xE', '\xE', 
		'\xE', '\xA4', '\x3', '\xF', '\x6', '\xF', '\xA8', '\n', '\xF', '\r', 
		'\xF', '\xE', '\xF', '\xA9', '\x3', '\x10', '\x3', '\x10', '\x6', '\x10', 
		'\xAE', '\n', '\x10', '\r', '\x10', '\xE', '\x10', '\xAF', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\xB6', '\n', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\a', 
		'\x39', 'N', 'T', '^', 'g', '\x2', '\x14', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x2', '\t', '\x2', '\v', '\x2', '\r', '\x5', '\xF', '\x6', '\x11', 
		'\x2', '\x13', '\x2', '\x15', '\x2', '\x17', '\x2', '\x19', '\x2', '\x1B', 
		'\x2', '\x1D', '\x2', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\a', 
		'\x3', '\x2', '\xF', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x3', '\x2', ',', ',', '\x3', '\x2', '}', '}', '\x3', '\x2', '\f', 
		'\f', '\x4', '\x2', '\f', '\f', ')', ')', '\x3', '\x2', '\x32', '\x33', 
		'\x3', '\x2', '\x32', '\x39', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '-', '-', '/', '/', 
		'\x4', '\x2', 'G', 'G', 'g', 'g', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x2', '\xC9', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\'', '\x3', '\x2', '\x2', '\x2', '\x5', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', '\t', 'Z', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'l', '\x3', '\x2', '\x2', '\x2', '\r', 
		'u', '\x3', '\x2', '\x2', '\x2', '\xF', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x84', '\x3', '\x2', '\x2', '\x2', '\x13', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x17', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\xAB', '\x3', '\x2', '\x2', '\x2', '!', '\xB1', 
		'\x3', '\x2', '\x2', '\x2', '#', '\xB3', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\'', '+', '\t', '\x2', '\x2', '\x2', 
		'(', '*', '\t', '\x3', '\x2', '\x2', ')', '(', '\x3', '\x2', '\x2', '\x2', 
		'*', '-', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', 
		'+', ',', '\x3', '\x2', '\x2', '\x2', ',', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '-', '+', '\x3', '\x2', '\x2', '\x2', '.', '\x32', '\x5', '\a', 
		'\x4', '\x2', '/', '\x32', '\x5', '\t', '\x5', '\x2', '\x30', '\x32', 
		'\x5', '\v', '\x6', '\x2', '\x31', '.', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x6', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', 
		'*', '\x2', '\x2', '\x34', '\x35', '\a', ',', '\x2', '\x2', '\x35', 'N', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\x38', '\a', '*', '\x2', '\x2', '\x37', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x38', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\x3', '\x2', '\x2', '\x2', '\x39', '\x37', '\x3', 
		'\x2', '\x2', '\x2', ':', '<', '\x3', '\x2', '\x2', '\x2', ';', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '<', 'M', '\x5', '\x5', '\x3', '\x2', '=', 
		'?', '\a', '*', '\x2', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', '?', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', '\x43', '\x45', '\a', 
		',', '\x2', '\x2', '\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'H', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\x3', '\x2', '\x2', '\x2', 'G', 'J', '\x3', '\x2', 
		'\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 'I', '@', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\x46', '\x3', '\x2', '\x2', '\x2', 'J', 'K', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'M', '\n', '\x4', '\x2', '\x2', 'L', 
		'\x39', '\x3', '\x2', '\x2', '\x2', 'L', 'I', '\x3', '\x2', '\x2', '\x2', 
		'M', 'P', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 
		'N', 'L', '\x3', '\x2', '\x2', '\x2', 'O', 'T', '\x3', '\x2', '\x2', '\x2', 
		'P', 'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\a', ',', '\x2', '\x2', 
		'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'V', '\x3', '\x2', '\x2', '\x2', 
		'T', 'U', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 
		'U', 'W', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\a', ',', '\x2', '\x2', 'X', 'Y', '\a', '+', '\x2', '\x2', 
		'Y', '\b', '\x3', '\x2', '\x2', '\x2', 'Z', '^', '\a', '}', '\x2', '\x2', 
		'[', ']', '\n', '\x5', '\x2', '\x2', '\\', '[', '\x3', '\x2', '\x2', '\x2', 
		']', '`', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', 
		'^', '\\', '\x3', '\x2', '\x2', '\x2', '_', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '`', '^', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\x5', '\x5', 
		'\x3', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x63', 'g', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x66', '\n', '\x5', '\x2', '\x2', '\x65', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'i', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x3', 
		'\x2', '\x2', '\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', 
		'\x7F', '\x2', '\x2', 'k', '\n', '\x3', '\x2', '\x2', '\x2', 'l', 'm', 
		'\a', '\x31', '\x2', '\x2', 'm', 'n', '\a', '\x31', '\x2', '\x2', 'n', 
		'r', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\n', '\x6', '\x2', '\x2', 
		'p', 'o', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		's', '\f', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'y', '\a', ')', '\x2', '\x2', 'v', 'x', '\n', '\a', '\x2', 
		'\x2', 'w', 'v', '\x3', '\x2', '\x2', '\x2', 'x', '{', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', 
		'\x2', 'z', '|', '\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\a', ')', '\x2', '\x2', '}', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x81', '\x5', '\x11', '\t', '\x2', '\x7F', '\x81', '\x5', 
		'\x13', '\n', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x85', '\x5', '\x15', '\v', '\x2', '\x83', '\x85', '\x5', 
		'\x17', '\f', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x87', '\x5', '!', '\x11', '\x2', '\x87', '\x88', '\x5', 
		'\x11', '\t', '\x2', '\x88', '\x14', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8E', '\x5', '\x1D', '\xF', '\x2', '\x8A', '\x8E', '\x5', '\x19', '\r', 
		'\x2', '\x8B', '\x8E', '\x5', '\x1F', '\x10', '\x2', '\x8C', '\x8E', '\x5', 
		'\x1B', '\xE', '\x2', '\x8D', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x98', '\x5', '\x1D', '\xF', '\x2', '\x90', 
		'\x91', '\a', '\x30', '\x2', '\x2', '\x91', '\x93', '\x5', '\x1D', '\xF', 
		'\x2', '\x92', '\x94', '\x5', '#', '\x12', '\x2', '\x93', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x95', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x99', '\x5', '#', '\x12', '\x2', '\x98', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x98', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x18', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9C', '\a', 
		'\'', '\x2', '\x2', '\x9B', '\x9D', '\t', '\b', '\x2', '\x2', '\x9C', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA2', '\a', '(', '\x2', '\x2', '\xA1', '\xA3', '\t', '\t', '\x2', '\x2', 
		'\xA2', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', 
		'\x3', '\x2', '\x2', '\x2', '\xA5', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\xA6', '\xA8', '\t', '\n', '\x2', '\x2', '\xA7', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', 
		'\xAA', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAD', '\a', '&', 
		'\x2', '\x2', '\xAC', '\xAE', '\t', '\v', '\x2', '\x2', '\xAD', '\xAC', 
		'\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', '\xB0', ' ', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', 
		'\t', '\f', '\x2', '\x2', '\xB2', '\"', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xB5', '\t', '\r', '\x2', '\x2', '\xB4', '\xB6', '\x5', '!', '\x11', 
		'\x2', '\xB5', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB8', '\x5', '\x1D', '\xF', '\x2', '\xB8', '$', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xBA', '\t', '\xE', '\x2', '\x2', '\xBA', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x2', '+', '\x31', '\x39', '@', '\x46', 
		'I', 'L', 'N', 'T', '^', '\x62', 'g', 'r', 'y', '\x80', '\x84', '\x8D', 
		'\x93', '\x95', '\x98', '\x9E', '\xA4', '\xA9', '\xAF', '\xB5', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
